// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://woxlfyovnvzxakyqviey.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndveGxmeW92bnZ6eGFreXF2aWV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTI5NjksImV4cCI6MjA2NTQ4ODk2OX0.OHT1gyaTeHAF-xpw5kf2T3HAndBzi4SwEB4CX4jhf9U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);